### ISSUE TITLE
Error when installing on Ubuntu (installs and works but has an error)

### ISSUE THREAD

**Issue by BrandtH22** [xch-dev/sage#16]
Error when installing on Ubuntu (installs and works without issue but error is present):
`N: Download is performed unsandboxed as root as file '/home/dev/Downloads/Sage_0.1.0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`

**Comment by Rigidity** [comment]
This is just a notice, not an error:
https://www.reddit.com/r/linux4noobs/comments/ux6cwx/installation_errors_on_deb_files_apt/
