### ISSUE TITLE
Add pending spend identifier to coins in transactions

### ISSUE THREAD

**Issue by BrandtH22** [xch-dev/sage#23]
Add pending spend identifier to coins in transactions

**Comment by Rigidity** [comment]
Thanks, this should now be implemented. When you make a transaction it will "lock" the coins and remove them from the spendable balance. They will be removed from the unspent coins when filtered, and the Spent column on the coin table will include the transaction id. If the coin is spent, the pending transaction will be removed from the list and the new coins will be created, increasing the balance again.

This system also uses a queue to resubmit transactions after a few minutes, and opens up opportunities for Replace By Fee in the future.
