### ISSUE TITLE
Receive Address blank on creation of a new wallet

### ISSUE THREAD

**Issue by MadderHat** [xch-dev/sage#41]
With a fresh install of 0.3.0 on Windows 11 on ARM64 using setup.exe installer, once a new wallet is created and loaded, the receive address is blank. The copy button successfully copies nothing.
Logging out of the wallet and logging back in populates the receive address and the copy button successfully copies the address listed.

**Comment by Rigidity** [comment]
Should be fixed soon by https://github.com/xch-dev/sage/pull/44
