### ISSUE TITLE
Navigation Issue - Unable to return to original starting point using "back" button.

### ISSUE THREAD

**Issue by thesemaphoreslim** [xch-dev/sage#9]
To duplicate, start at the Wallet screen listing all coins.  Then click the hamburger menu and select Settings.  Then click the Network icon.  From here, clicking the "back" button at the top left just toggles you between Settings and Network List.  You are unable to return to the Wallet/Tokens/NFTs screen without logging out.  The "back" button should return you to the original starting point.

**Comment by Rigidity** [comment]
Thanks, I hadn't tested this page in a while.
